import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '@/shared/styles/global.scss'
import { Header } from '@/widgets/header'
import { Footer } from '@/widgets/footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html suppressHydrationWarning lang="en">
      <body className={inter.className}>
          <Header/>
        {children}
        <Footer/>
        </body>
    </html>
  )
}
